"use client";
import { FormEvent, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import styles from "./incident-workspace.module.css";
export function IncidentRecordControls({ eventId, incidentId, reference, isAdmin, title, initialReport }: { eventId:string; incidentId:string; reference:string; isAdmin:boolean; title:string; initialReport:string }) {
  const dialog = useRef<HTMLDialogElement>(null); const editDialog = useRef<HTMLDialogElement>(null); const [error,setError]=useState<string>(); const [busy,setBusy]=useState(false); const router=useRouter();
  async function edit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const r=await fetch(`/api/events/${eventId}/incidents/${incidentId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:f.get("title"),initialReport:f.get("initialReport")})});setBusy(false);if(!r.ok){setError((await r.json()).error);return;}editDialog.current?.close();router.refresh();}
  async function archive(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const r=await fetch(`/api/events/${eventId}/incidents/${incidentId}/archive`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:f.get("password"),reference:f.get("reference"),reason:f.get("reason")})});setBusy(false);if(!r.ok){setError((await r.json()).error);return;}router.push(`/events/${eventId}/control`);router.refresh();}
  return <div className={styles.recordControls}><button className={styles.secondaryControl} onClick={()=>editDialog.current?.showModal()}>Edit incident</button><dialog ref={editDialog} className={styles.archiveDialog}><form onSubmit={edit}><p className={styles.eyebrow}>Governed record change</p><h2>Edit incident</h2><label className="field-label">Title<input className="text-input" name="title" defaultValue={title} required /></label><label className="field-label">Initial report<textarea className="text-input" name="initialReport" defaultValue={initialReport} /></label>{error?<p className={styles.saveError}>{error}</p>:null}<button className="primary-button" disabled={busy}>{busy?"Saving…":"Save changes"}</button></form></dialog>{isAdmin ? <><button className={styles.archiveControl} onClick={()=>dialog.current?.showModal()}>Archive incident</button><dialog ref={dialog} className={styles.archiveDialog}><form onSubmit={archive}><p className={styles.eyebrow}>Administrator confirmation</p><h2>Archive incident</h2><p>It will leave live Event Control. Its chronology and audit record remain.</p><label className="field-label">Reason<textarea className="text-input" name="reason" required /></label><label className="field-label">Type {reference}<input className="text-input" name="reference" required /></label><label className="field-label">Your current password<input className="text-input" type="password" name="password" required /></label>{error?<p className={styles.saveError}>{error}</p>:null}<button className={styles.archiveControl} disabled={busy}>{busy?"Archiving…":"Archive incident"}</button></form></dialog></>:null}</div>;
}
